In [66]:
import pandas as pd;
df = pd.read_csv("sales_large-3.csv",parse_dates=['order_date'])

In [56]:
delivered = df[df['status'] == "Delivered"]

In [57]:
df.head()

,order_id,customer_id,order_date,category,product,price,quantity,region,status
0,101,1,2026-01-01,Electronics,Laptop,55000,1,South,Delivered
1,102,2,2026-02-01,Electronics,Mouse,1200,2,North,Delivered
2,103,3,2026-03-01,Furniture,Chair,3000,1,East,Delivered
3,104,1,2026-04-01,Electronics,Mobile,20000,1,South,Pending
4,105,4,2026-05-01,Furniture,Table,8000,1,West,Delivered

In [58]:
filtered = df[(df['category'] == 'Electronics') & 
              (df['region'] == 'North') & 
              (df['status'] == 'Delivered')]

filtered

,order_id,customer_id,order_date,category,product,price,quantity,region,status
1,102,2,2026-02-01,Electronics,Mouse,1200,2,North,Delivered
5,106,2,2026-06-01,Electronics,Headphone,2000,3,North,Delivered

In [59]:
df['revenue'] = df['price']*df['quantity']

In [60]:
df['shipping_fee'] = df['revenue'].apply(lambda x:500 if x < 5000 else 0)

In [61]:
summary = df.groupby('category').agg({'revenue':['sum','mean'],'quantity' :'sum'})
#  in agg we need to put in a dictionary wise 
# key is the column and list of functions for the operations 
summary

            revenue               quantity
                sum          mean      sum
category
Electronics  174600  24942.857143       11
Furniture     36000  12000.000000        3

In [62]:
summary = summary.reset_index()

In [63]:
df

,order_id,customer_id,order_date,category,product,price,quantity,region,status,revenue,shipping_fee
0,101,1,2026-01-01,Electronics,Laptop,55000,1,South,Delivered,55000,0
1,102,2,2026-02-01,Electronics,Mouse,1200,2,North,Delivered,2400,500
2,103,3,2026-03-01,Furniture,Chair,3000,1,East,Delivered,3000,500
3,104,1,2026-04-01,Electronics,Mobile,20000,1,South,Pending,20000,0
4,105,4,2026-05-01,Furniture,Table,8000,1,West,Delivered,8000,0
5,106,2,2026-06-01,Electronics,Headphone,2000,3,North,Delivered,6000,0
6,107,5,2026-07-01,Electronics,Laptop,54000,1,East,Delivered,54000,0
7,108,3,2026-08-01,Furniture,Sofa,25000,1,South,Cancelled,25000,0
8,109,4,2026-09-01,Electronics,Tablet,18000,2,West,Delivered,36000,0
9,110,1,2026-10-01,Electronics,Mouse,1200,1,South,Delivered,1200,500

In [64]:
top_products = df.groupby('product')['revenue'].sum().sort_values(ascending=False)

In [65]:
df['month'] = df['order_date'].dt.to_period("M")

In [49]:
monthy_sales = df.groupby('month')['revenue'].sum()

In [50]:
monthy_sales

month
2026-01    55000
2026-02     2400
2026-03     3000
2026-04    20000
2026-05     8000
2026-06     6000
2026-07    54000
2026-08    25000
2026-09    36000
2026-10     1200
Freq: M, Name: revenue, dtype: int64